names = [
    'João Silva',
    'Maria Santos',
    'Pedro Oliveira',
    'Ana Souza',
    'Lucas Pereira',
    'Juliana Costa',
    'Marcos Rodrigues',
    'Fernanda Almeida',
    'Rafael Ferreira',
    'Laura Carvalho',
    'Bruno Martins',
    'Camila Cardoso',
    'Tiago Santos',
    'Amanda Oliveira',
    'Diego Lima',
    'Jéssica Gonçalves',
    'Guilherme Silva',
    'Carolina Vieira',
    'Gabriel Pereira',
    'Larissa Santos',
    'André Almeida',
    'Isabela Rodrigues',
    'Leonardo Sousa',
    'Beatriz Lima',
    'Vinícius Oliveira',
    'Letícia Fernandes',
    'Marcelo Costa',
    'Bianca Ribeiro',
    'Matheus Mendes',
    'Giovanna Silva'
]

telephone = [
    '+55 11 91234-5678',
    '+55 21 98765-4321',
    '+55 81 99876-5432',
    '+55 47 95432-1876',
    '+55 31 92345-6789',
    '+55 51 98765-4321',
    '+55 85 91234-5678',
    '+55 41 95432-1876',
    '+55 62 99876-5432',
    '+55 71 92345-6789',
    '+55 54 98765-4321',
    '+55 91 91234-5678',
    '+55 84 95432-1876',
    '+55 48 99876-5432',
    '+55 81 92345-6789',
    '+55 65 98765-4321',
    '+55 92 91234-5678',
    '+55 69 95432-1876',
    '+55 79 99876-5432',
    '+55 98 92345-6789',
]

emails = [
    'joao.silva@gmail.com',
    'maria.santos@gmail.com',
    'pedro.oliveira@gmail.com',
    'ana.souza@gmail.com',
    'lucas.pereira@gmail.com',
    'juliana.costa@gmail.com',
    'marcos.rodrigues@gmail.com',
    'fernanda.almeida@gmail.com',
    'rafael.ferreira@gmail.com',
    'laura.carvalho@gmail.com',
    'bruno.martins@yahoo.com',
    'camila.cardoso@yahoo.com',
    'tiago.santos@yahoo.com',
    'amanda.oliveira@yahoo.com',
    'diego.lima@yahoo.com',
    'jessica.goncalves@yahoo.com',
    'guilherme.silva@yahoo.com',
    'carolina.vieira@yahoo.com',
    'gabriel.pereira@yahoo.com',
    'larissa.santos@yahoo.com',
    'andre.almeida@hotmail.com',
    'isabela.rodrigues@hotmail.com',
    'leonardo.sousa@hotmail.com',
    'beatriz.lima@hotmail.com',
    'vinicius.oliveira@hotmail.com',
    'leticia.fernandes@hotmail.com',
    'marcelo.costa@hotmail.com',
    'bianca.ribeiro@hotmail.com',
    'matheus.mendes@hotmail.com',
    'giovanna.silva@hotmail.com',
]

state = [
    'Acre', 
    'Alagoas', 
    'Amapá', 
    'Amazonas', 
    'Bahia', 
    'Ceará', 
    'Distrito Federal', 
    'Espírito Santo', 
    'Goiás', 
    'Maranhão', 
    'Mato Grosso', 
    'Mato Grosso do Sul', 
    'Minas Gerais', 
    'Pará', 
    'Paraíba', 
    'Paraná', 
    'Pernambuco', 
    'Piauí', 
    'Rio de Janeiro', 
    'Rio Grande do Norte', 
    'Rio Grande do Sul', 
    'Rondônia', 
    'Roraima', 
    'Santa Catarina', 
    'São Paulo', 
    'Sergipe', 
    'Tocantins'
]

cityByState = {
    'Acre': ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira'],
    'Alagoas': ['Maceió', 'Arapiraca', 'Palmeira dos Índios'],
    'Amapá': ['Macapá', 'Santana', 'Laranjal do Jari'],
    'Amazonas': ['Manaus', 'Parintins', 'Itacoatiara'],
    'Bahia': ['Salvador', 'Feira de Santana', 'Vitória da Conquista'],
    'Ceará': ['Fortaleza', 'Caucaia', 'Juazeiro do Norte'],
    'Distrito Federal': ['Brasília', 'Ceilândia', 'Taguatinga'],
    'Espírito Santo': ['Vitória', 'Vila Velha', 'Serra'],
    'Goiás': ['Goiânia', 'Aparecida de Goiânia', 'Anápolis'],
    'Maranhão': ['São Luís', 'Imperatriz', 'São José de Ribamar'],
    'Mato Grosso': ['Cuiabá', 'Várzea Grande', 'Rondonópolis'],
    'Mato Grosso do Sul': ['Campo Grande', 'Dourados', 'Três Lagoas'],
    'Minas Gerais': ['Belo Horizonte', 'Uberlândia', 'Contagem'],
    'Pará': ['Belém', 'Ananindeua', 'Santarém'],
    'Paraíba': ['João Pessoa', 'Campina Grande', 'Santa Rita'],
    'Paraná': ['Curitiba', 'Londrina', 'Maringá'],
    'Pernambuco': ['Recife', 'Jaboatão dos Guararapes', 'Olinda'],
    'Piauí': ['Teresina', 'Parnaíba', 'Picos'],
    'Rio de Janeiro': ['Rio de Janeiro', 'São Gonçalo', 'Duque de Caxias'],
    'Rio Grande do Norte': ['Natal', 'Mossoró', 'Parnamirim'],
    'Rio Grande do Sul': ['Porto Alegre', 'Caxias do Sul', 'Pelotas'],
    'Rondônia': ['Porto Velho', 'Ji-Paraná', 'Ariquemes'],
    'Roraima': ['Boa Vista', 'Rorainópolis', 'Caracaraí'],
    'Santa Catarina': ['Florianópolis', 'Joinville', 'Blumenau'],
    'São Paulo': ['São Paulo', 'Guarulhos', 'Campinas'],
    'Sergipe': ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto'],
    'Tocantins': ['Palmas', 'Araguaína', 'Gurupi']
}
